
// Mock API function
import type {JobDef, ScheduleItem} from "@/types/schedule.ts";

export const performJobAction = async (
  action: "resume" | "pause" | "delete",
  job: JobDef
) => {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1000));
  console.log(`API CALL: ${action.toUpperCase()} job: ${job.name} (Group: ${job.group})`);
  return { success: true };
};

// Generate 32 Mock Items
const autoGeneratedData = Array.from({length: 32}, (_, i) => {
  const groups = ["Notification", "Maintenance", "Reporting", "Data"] as const;
  const group = groups[i % 4];
  const index = i + 1;

  return {
    id: `job-${index}`,
    name: `${group}Job_${index}`,
    group: group,
    description: `Automated ${group.toLowerCase()} task number ${index}.`,
    expectedJobDataParameters: [
      {
        name: "targetId",
        description: "The target identifier for operation.",
        required: true,
        array: false,
      },
      {
        name: "options",
        description: "Additional execution flags.",
        required: false,
        array: true,
      },
    ],
  };
});
export const actualData = [
  {
    name: "SmsJob",
    group: "Notification",
    description: "Sends SMS notifications based on jobV2 parameters.",
    expectedJobDataParameters: [
      {
        name: "phoneNo",
        description: "The phone number to which the SMS will be sent.",
        required: true,
        array: false
      }
    ]
  },
  {
    name: "EmailJob",
    group: "Notification",
    description: "Sends email notifications based on jobV2 parameters.",
    expectedJobDataParameters: [
      {
        name: "subject",
        description: "The subject line of the email.",
        required: true,
        array: false
      },
      {
        name: "body",
        description: "The main content/body of the email.",
        required: true,
        array: false
      },
      {
        name: "toRecipients",
        description: "Comma-separated list of recipient email addresses (e.g., 'a@example.com,b@example.com').",
        required: true,
        array: true
      },
      {
        name: "ccRecipients",
        description: "Comma-separated list of CC recipient email addresses.",
        required: false,
        array: true
      }
    ]
  }
];
export const jobsData: JobDef[] = actualData;

// Schedule List
export const MOCK_SCHEDULE_DATA: ScheduleItem[] = [
  {
    jobGroup: "Notification",
    jobName: "SmsJob",
    jobDescription: "Job for SmsJob in group Notification",
    triggerGroup: "Notification",
    triggerName: "sms-2",
    triggerState: "NORMAL",
    triggerType: "Cron",
    nextFireTime: "2026-02-05T15:45:00.000+00:00",
    previousFireTime: null,
    startTime: "2026-02-05T15:43:58.000+00:00",
    endTime: null,
    triggerDataMap: { phoneNo: "09965122877" },
    simpleTriggerRepeatCount: null,
    simpleTriggerRepeatInterval: null,
    cronExpression: "0 0/3 * * * ?",
  },
  {
    jobGroup: "Notification",
    jobName: "SmsJob",
    jobDescription: "Job for SmsJob in group Notification",
    triggerGroup: "Notification",
    triggerName: "sms-5",
    triggerState: "NORMAL",
    triggerType: "Simple",
    nextFireTime: "2026-02-25T16:43:00.000+00:00",
    previousFireTime: null,
    startTime: "2026-02-25T16:43:00.000+00:00",
    endTime: "2026-02-25T20:53:00.000+00:00",
    triggerDataMap: { phoneNo: "09965122877" },
    simpleTriggerRepeatCount: 20,
    simpleTriggerRepeatInterval: 120000,
    cronExpression: null,
  },
  {
    jobGroup: "Notification",
    jobName: "EmailJob",
    jobDescription: "Job for EmailJob in group Notification",
    triggerGroup: "Notification",
    triggerName: "email-1",
    triggerState: "NORMAL",
    triggerType: "Simple",
    nextFireTime: "2026-02-05T15:45:00.000+00:00",
    previousFireTime: "2026-02-05T15:44:00.000+00:00",
    startTime: "2026-02-05T15:43:00.000+00:00",
    endTime: "2026-02-25T21:05:00.000+00:00",
    triggerDataMap: {
      toRecipients: "NN,AA,BB",
      subject: "report_for_email-4",
      ccRecipients: "CC,EE",
      body: "Hello World",
    },
    simpleTriggerRepeatCount: 20,
    simpleTriggerRepeatInterval: 60000,
    cronExpression: null,
  },
  {
    jobGroup: "Report", // Changed group to demonstrate filtering
    jobName: "DailyReport",
    jobDescription: "Daily system check",
    triggerGroup: "Report",
    triggerName: "sys-check-1",
    triggerState: "PAUSED",
    triggerType: "Cron",
    nextFireTime: "2026-02-24T20:43:00.000+00:00",
    previousFireTime: null,
    startTime: "2026-02-24T20:43:00.000+00:00",
    endTime: null,
    triggerDataMap: { systemId: "SYS-001" },
    simpleTriggerRepeatCount: null,
    simpleTriggerRepeatInterval: null,
    cronExpression: "0 0 12 * * ?",
  },
];