
// Mock API function
import type {JobDef, ScheduleItem} from "@/types/schedule.ts";

export const performJobAction = async (
  action: "resume" | "pause" | "delete",
  job: JobDef
) => {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1000));
  console.log(`API CALL: ${action.toUpperCase()} job: ${job.name} (Group: ${job.group})`);
  return { success: true };
};

// Generate 32 Mock Items
const autoGeneratedData = Array.from({length: 32}, (_, i) => {
  const groups = ["Notification", "Maintenance", "Reporting", "Data"] as const;
  const group = groups[i % 4];
  const index = i + 1;

  return {
    id: `job-${index}`,
    name: `${group}Job_${index}`,
    group: group,
    description: `Automated ${group.toLowerCase()} task number ${index}.`,
    expectedJobDataParameters: [
      {
        name: "targetId",
        description: "The target identifier for operation.",
        required: true,
        array: false,
      },
      {
        name: "options",
        description: "Additional execution flags.",
        required: false,
        array: true,
      },
    ],
  };
});
export const actualData = [
  {
    name: "SmsJob",
    group: "Notification",
    description: "Sends SMS notifications based on jobV2 parameters.",
    expectedJobDataParameters: [
      {
        name: "phoneNo",
        description: "The phone number to which the SMS will be sent.",
        required: true,
        array: false
      }
    ]
  },
  {
    name: "EmailJob",
    group: "Notification",
    description: "Sends email notifications based on jobV2 parameters.",
    expectedJobDataParameters: [
      {
        name: "subject",
        description: "The subject line of the email.",
        required: true,
        array: false
      },
      {
        name: "body",
        description: "The main content/body of the email.",
        required: true,
        array: false
      },
      {
        name: "toRecipients",
        description: "Comma-separated list of recipient email addresses (e.g., 'a@example.com,b@example.com').",
        required: true,
        array: true
      },
      {
        name: "ccRecipients",
        description: "Comma-separated list of CC recipient email addresses.",
        required: false,
        array: true
      }
    ]
  }
];
export const jobsData: JobDef[] = actualData;
